---
- name: Setup Development Environment
  hosts: localhost
  connection: local
  become: yes
  become_method: sudo
  vars:
    repo_url: "https://github.com/meetorman/terminal-god.git"
    config_dir: "{{ ansible_env.HOME }}/.config/nvim"

  tasks:
    - name: Clone terminal-god repository
      git:
        repo: "{{ repo_url }}"
        dest: "{{ config_dir }}"
        version: main

    - name: Create symbolic link for tmux config
      file:
        src: "{{ config_dir }}/.tmux.conf"
        dest: "{{ ansible_env.HOME }}/.tmux.conf"
        state: link

    - name: Install Homebrew packages (run as non-root)
      become: no  # Don't use sudo for Homebrew tasks
      community.general.homebrew:
        name:
          - tmux
          - nvim
          - wget
          - mercurial
          - ripgrep
          - fd
          - black
          - isort
          - stylua
          - php
          - julia
          - composer
          - rust
          - go
          - openjdk
        state: present

    - name: Install GNU tar
      become: no
      homebrew:
        name: gnu-tar
        state: present

    - name: Download and extract Lua
      unarchive:
        src: https://www.lua.org/ftp/lua-5.1.5.tar.gz
        dest: /tmp
        remote_src: yes
      environment:
        PATH: /usr/local/opt/gnu-tar/libexec/gnubin:{{ ansible_env.PATH }}

    - name: Build and install Lua
      shell:
        cmd: |
          cd /tmp/lua-5.1.5
          make macosx
          make install
        creates: /usr/local/bin/lua

    - name: Download and extract LuaRocks
      unarchive:
        src: https://luarocks.github.io/luarocks/releases/luarocks-3.11.1.tar.gz
        dest: /tmp
        remote_src: yes
      environment:
        PATH: /usr/local/opt/gnu-tar/libexec/gnubin:{{ ansible_env.PATH }}

    - name: Configure, build, and install LuaRocks
      shell:
        cmd: |
          cd /tmp/luarocks-3.11.1
          ./configure --with-lua=/usr/local/ --lua-version=5.1
          make
          make install
        creates: /usr/local/bin/luarocks

    - name: Install global npm packages
      npm:
        name: "{{ item }}"
        global: yes
      loop:
        - neovim
        - prettier
      become: no  # Don't use sudo for npm global installs

    - name: Check OpenJDK installation path
      stat:
        path: /opt/homebrew/opt/openjdk/libexec/openjdk.jdk
      register: openjdk_path

    - name: Create symlink for Java (Apple Silicon)
      file:
        src: /opt/homebrew/opt/openjdk/libexec/openjdk.jdk
        dest: /Library/Java/JavaVirtualMachines/openjdk.jdk
        state: link
      when: openjdk_path.stat.exists
      become: yes

    - name: Check OpenJDK installation path (Intel fallback)
      stat:
        path: /usr/local/opt/openjdk/libexec/openjdk.jdk
      register: openjdk_path_intel
      when: not openjdk_path.stat.exists

    - name: Create symlink for Java (Intel Mac)
      file:
        src: /usr/local/opt/openjdk/libexec/openjdk.jdk
        dest: /Library/Java/JavaVirtualMachines/openjdk.jdk
        state: link
      when: 
        - not openjdk_path.stat.exists
        - openjdk_path_intel.stat.exists
      become: yes

    - name: Print warning if OpenJDK not found
      debug:
        msg: "WARNING: OpenJDK installation not found. Please ensure it's installed via Homebrew."
      when: 
        - not openjdk_path.stat.exists
        - not openjdk_path_intel.stat.exists

    - name: Install neovim Python package
      pip:
        name: neovim
        extra_args: --break-system-package

- name: Finalize setup
  hosts: localhost
  connection: local
  tasks:
    - name: Print setup complete message
      debug:
        msg: "Setup complete. Please restart your terminal or run 'source ~/.zshrc'"

