---
- name: Setup Development Environment
  hosts: localhost
  connection: local
  become: yes
  vars:
    repo_url: "https://github.com/meetorman/terminal-god.git"

  tasks:

    - name: Get the user's home directory
      debug:
        msg: "{{ ansible_env.HOME }}"
      register: user_home  # Register the output for later use
      become: no  # Ensure this runs as the intended user
    - name: Ensure ~/.config directory exists
      file:
        path: "{{ user_home }}/.config"
        state: directory
        mode: '00755'
      become: no  # Do not run as root

    - name: Debug user home directory
      debug:
        var: user_home

    - name: Remove existing ~/.config/nvim if it exists
      file:
        path: "{{ user_home }}/.config/nvim"
        state: absent
      become: no  # Do not run as root

    - name: Clone terminal-god repository into ~/.config/nvim
      git:
        repo: "{{ repo_url }}"
        dest: "{{ user_home }}/.config/nvim"
        version: main
        force: yes
      become: no  # Do not run as root

    - name: Create symbolic link for tmux config
      file:
        src: "{{ user_home }}/.config/nvim/.tmux.conf"
        dest: "{{ user_home }}/.tmux.conf"
        state: link
      become: no  # Do not run as root

    - name: Install Homebrew packages
      community.general.homebrew:
        name:
          - tmux
          - nvim
          - wget
          - mercurial
          - ripgrep
          - fd
          - black
          - isort
          - stylua
          - php
          - julia
          - composer
          - rust
          - go
          - openjdk
        state: present
      become: yes  # Run as root

    - name: Install GNU tar
      community.general.homebrew:
        name: gnu-tar
        state: present
      become: yes  # Run as root

    - name: Download and extract Lua
      unarchive:
        src: https://www.lua.org/ftp/lua-5.1.5.tar.gz
        dest: /tmp
        remote_src: yes
      environment:
        PATH: /usr/local/opt/gnu-tar/libexec/gnubin:{{ ansible_env.PATH }}

    - name: Build and install Lua
      shell: |
        cd /tmp/lua-5.1.5
        make macosx
        make install
      args:
        creates: /usr/local/bin/lua
      become: yes  # Run as root

    - name: Download and extract LuaRocks
      unarchive:
        src: https://luarocks.github.io/luarocks/releases/luarocks-3.11.1.tar.gz
        dest: /tmp
        remote_src: yes
      environment:
        PATH: /usr/local/opt/gnu-tar/libexec/gnubin:{{ ansible_env.PATH }}

    - name: Configure, build, and install LuaRocks
      shell: |
        cd /tmp/luarocks-3.11.1
        ./configure --with-lua=/usr/local/ --lua-version=5.1
        make
        make install
      args:
        creates: /usr/local/bin/luarocks
      become: yes  # Run as root

    - name: Install global npm packages
      npm:
        name: "{{ item }}"
        global: yes
      loop:
        - neovim
        - prettier
      become: no  # Don't use sudo for npm global installs

    - name: Check OpenJDK installation path
      stat:
        path: /opt/homebrew/opt/openjdk/libexec/openjdk.jdk
      register: openjdk_path

    - name: Create symlink for Java (Apple Silicon)
      file:
        src: /opt/homebrew/opt/openjdk/libexec/openjdk.jdk
        dest: /Library/Java/JavaVirtualMachines/openjdk.jdk
        state: link
      when: openjdk_path.stat.exists
      become: yes  # Run as root

    - name: Check OpenJDK installation path (Intel fallback)
      stat:
        path: /usr/local/opt/openjdk/libexec/openjdk.jdk
      register: openjdk_path_intel
      when: not openjdk_path.stat.exists

    - name: Create symlink for Java (Intel Mac)
      file:
        src: /usr/local/opt/openjdk/libexec/openjdk.jdk
        dest: /Library/Java/JavaVirtualMachines/openjdk.jdk
        state: link
      when: 
        - not openjdk_path.stat.exists
        - openjdk_path_intel.stat.exists
      become: yes  # Run as root

    - name: Print warning if OpenJDK not found
      debug:
        msg: "WARNING: OpenJDK installation not found. Please ensure it's installed via Homebrew."
      when: 
        - not openjdk_path.stat.exists
        - not openjdk_path_intel.stat.exists

    - name: Install neovim Python package
      pip:
        name: neovim
        extra_args: --break-system-package
      become: yes  # Run as root

- name: Finalize setup
  hosts: localhost
  connection: local
  tasks:
    - name: Print setup complete message
      debug:
        msg: "Setup complete. Please restart your terminal or run 'source ~/.zshrc'"
