name: Publish LuaRocks

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Lua
      uses: leafo/gh-actions-lua@v8
      with:
        luaVersion: "5.1"

    - name: Set up LuaRocks
      uses: leafo/gh-actions-luarocks@v4

    - name: Create rockspec
      run: |
        VERSION=$(git describe --tags --always)
        cat > terminal-god-$VERSION.rockspec << 'EOL'
        package = "terminal-god"
        version = "${VERSION}-1"
        source = {
           url = "git://github.com/${GITHUB_REPOSITORY}",
           tag = "${VERSION}"
        }
        description = {
           summary = "Terminal God - My Neovim configuration",
           detailed = [[
              This is a complete Neovim configuration package including all necessary
              plugins and settings for the Terminal God setup.
           ]],
           homepage = "https://github.com/${GITHUB_REPOSITORY}",
           license = "MIT"
        }
        dependencies = {
           "lua >= 5.1",
           -- List your dependencies here
        }
        build = {
           type = "make",
           build_variables = {
              CFLAGS="\$(CFLAGS)",
              LIBFLAG="\$(LIBFLAG)",
              LUA_LIBDIR="\$(LUA_LIBDIR)",
              LUA_BINDIR="\$(LUA_BINDIR)",
              LUA_INCDIR="\$(LUA_INCDIR)",
              LUA="\$(LUA)",
           },
           install_variables = {
              INST_PREFIX="\$(PREFIX)",
              INST_BINDIR="\$(BINDIR)",
              INST_LIBDIR="\$(LIBDIR)",
              INST_LUADIR="\$(LUADIR)",
              INST_CONFDIR="\$(CONFDIR)",
           },
        }
        EOL
        sed -i "s/\${VERSION}/$VERSION/g" terminal-god-$VERSION.rockspec
        sed -i "s/\${GITHUB_REPOSITORY}/$GITHUB_REPOSITORY/g" terminal-god-$VERSION.rockspec

    - name: Build rock
      run: |
        VERSION=$(git describe --tags --always)
        luarocks make terminal-god-$VERSION.rockspec

    - name: Publish to LuaRocks
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        VERSION=$(git describe --tags --always)
        luarocks config --local github_token $GITHUB_TOKEN
        luarocks upload terminal-god-$VERSION.rockspec --api-key=github