name: Publish LuaRocks

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Lua
      uses: leafo/gh-actions-lua@v8
      with:
        luaVersion: "5.1"

    - name: Set up LuaRocks
      uses: leafo/gh-actions-luarocks@v4

    - name: Create rockspec and Makefile
      run: |
        VERSION=$(git describe --tags --always)
        ROCKSPEC_VERSION="${VERSION}-1"
        ESCAPED_VERSION=$(echo $ROCKSPEC_VERSION | sed 's/[\/&]/\\&/g')
        ESCAPED_REPO=$(echo $GITHUB_REPOSITORY | sed 's/[\/&]/\\&/g')
        
        # Create rockspec
        cat > terminal-god-$ROCKSPEC_VERSION.rockspec << EOL
        package = "terminal-god"
        version = "$ROCKSPEC_VERSION"
        source = {
           url = "git://github.com/$GITHUB_REPOSITORY",
           tag = "$VERSION"
        }
        description = {
           summary = "Terminal God - My Neovim configuration",
           detailed = [[
              This is a complete Neovim configuration package including all necessary
              plugins and settings for the Terminal God setup.
           ]],
           homepage = "https://github.com/$GITHUB_REPOSITORY",
           license = "MIT"
        }
        dependencies = {
           "lua >= 5.1",
           -- List your dependencies here
        }
        build = {
           type = "make",
           install_variables = {
              INST_CONFDIR = "$(PWD)/install"
           },
        }
        EOL
        
        # Create Makefile
        cat > Makefile << EOL
        TERMINAL_GOD_DIR=\$(INST_CONFDIR)

        install:
        	mkdir -p \$(TERMINAL_GOD_DIR)
        	cp -R * \$(TERMINAL_GOD_DIR)

        uninstall:
        	rm -rf \$(TERMINAL_GOD_DIR)
        EOL

    - name: Debug information
      run: |
        echo "Workspace directory: $GITHUB_WORKSPACE"
        echo "Current directory: $(pwd)"
        echo "Contents of current directory:"
        ls -la
        echo "Rockspec content:"
        cat terminal-god-*.rockspec
        echo "Makefile content:"
        cat Makefile

    - name: Build rock
      run: |
        VERSION=$(git describe --tags --always)
        ROCKSPEC_VERSION="${VERSION}-1"
        luarocks make terminal-god-$ROCKSPEC_VERSION.rockspec --local

    - name: Publish to LuaRocks
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        VERSION=$(git describe --tags --always)
        ROCKSPEC_VERSION="${VERSION}-1"
        luarocks config --local github_token $GITHUB_TOKEN
        luarocks upload terminal-god-$ROCKSPEC_VERSION.rockspec --api-key=github