name: Publish LuaRocks

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Lua
      uses: leafo/gh-actions-lua@v8
      with:
        luaVersion: "5.1"

    - name: Set up LuaRocks
      uses: leafo/gh-actions-luarocks@v4

    - name: Create rockspec
      run: |
        VERSION=$(git describe --tags --always)
        ROCKSPEC_VERSION="${VERSION}-1"
        cat > terminal-god-$ROCKSPEC_VERSION.rockspec << EOL
        package = "terminal-god"
        version = "$ROCKSPEC_VERSION"
        source = {
           url = "git://github.com/$GITHUB_REPOSITORY",
           tag = "$VERSION"
        }
        description = {
           summary = "Terminal God - My Neovim configuration",
           detailed = [[
              This is a complete Neovim configuration package including all necessary
              plugins and settings for the Terminal God setup.
           ]],
           homepage = "https://github.com/$GITHUB_REPOSITORY",
           license = "MIT"
        }
        dependencies = {
           "lua >= 5.1",
        }
        build = {
           type = "copy",
           modules = {
              ["terminal-god"] = "init.lua",
           },
        }
        EOL

    - name: Build rock
      run: |
        VERSION=$(git describe --tags --always)
        ROCKSPEC_VERSION="${VERSION}-1"
        luarocks make terminal-god-$ROCKSPEC_VERSION.rockspec --local

    - name: Publish to LuaRocks
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        VERSION=$(git describe --tags --always)
        ROCKSPEC_VERSION="${VERSION}-1"
        luarocks config --local github_token $GITHUB_TOKEN
        luarocks upload terminal-god-$ROCKSPEC_VERSION.rockspec --api-key=github