name: Publish LuaRocks

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Lua
      uses: leafo/gh-actions-lua@v8
      with:
        luaVersion: "5.1"

    - name: Set up LuaRocks
      uses: leafo/gh-actions-luarocks@v4

    - name: Create rockspec
      run: |
        VERSION="0.1.$(git rev-list --count HEAD)"
        ROCKSPEC_VERSION="${VERSION}-2"
        cat > terminal-god-$ROCKSPEC_VERSION.rockspec << EOL
        package = "terminal-god"
        version = "$ROCKSPEC_VERSION"
        source = {
           url = "git://github.com/$GITHUB_REPOSITORY",
           tag = "v$VERSION"
        }
        description = {
           summary = "Terminal God - My Neovim configuration",
           detailed = [[
              This is a complete Neovim configuration package including all necessary
              plugins and settings for the Terminal God setup.
           ]],
           homepage = "https://github.com/$GITHUB_REPOSITORY",
           license = "MIT"
        }
        dependencies = {
           "lua >= 5.1",
        }
        build = {
           type = "builtin",
           modules = {},
        }
        EOL
        
        # Dynamically add all Lua files to the modules table
        echo "    modules = {" >> terminal-god-$ROCKSPEC_VERSION.rockspec
        find . -name "*.lua" | while read file; do
          module_name=$(echo $file | sed 's/^\.\/lua\//terminal-god./' | sed 's/\.lua$//' | sed 's/\//./g')
          echo "        [\"$module_name\"] = \"$file\"," >> terminal-god-$ROCKSPEC_VERSION.rockspec
        done
        echo "    }," >> terminal-god-$ROCKSPEC_VERSION.rockspec

    - name: Install JSON library
      run: luarocks install dkjson

    - name: Publish to LuaRocks
      env:
        LUAROCKS_API_KEY: ${{ secrets.LUAROCKS_API_KEY }}
      run: |
        VERSION="0.1.$(git rev-list --count HEAD)"
        ROCKSPEC_VERSION="${VERSION}-1"
        luarocks upload terminal-god-$ROCKSPEC_VERSION.rockspec --api-key=$LUAROCKS_API_KEY --force --skip-pack