name: Neovim Lazy.nvim Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Neovim
        run: |
          sudo apt-get update
          sudo add-apt-repository ppa:neovim-ppa/unstable -y
          sudo apt-get update
          sudo apt-get install -y neovim

      - name: Install Python and Node.js
        run: |
          sudo apt-get install -y python3-pip nodejs npm

      - name: Setup Neovim config
        run: |
          mkdir -p ~/.config/nvim
          cp -r ./* ~/.config/nvim/

      - name: Install Lazy.nvim
        run: |
          git clone --filter=blob:none https://github.com/folke/lazy.nvim.git --branch=stable ~/.local/share/nvim/lazy/lazy.nvim

      - name: Load Neovim plugins
        run: |
          nvim --headless -c "lua require('lazy').sync()" -c "qa"

      - name: Create a snapshot of installed plugins
        run: |
          nvim --headless -c "lua require('lazy').snapshot('lazy-lock.json')" -c "qa"

      - name: Switch to secure configuration
        run: |
          mv ~/.config/nvim/lua/core/lazy_secure.lua ~/.config/nvim/lua/core/lazy.lua

      - name: Package plugins
        run: |
          if [ -d "$HOME/.local/share/nvim/lazy" ]; then
            tar -czvf plugins.tar.gz -C $HOME/.local/share/nvim/lazy .
          else
            echo "Plugins directory not found. Skipping packaging."
            exit 1
          fi

      - name: Package configuration
        run: |
          mkdir nvim-config
          cp -r ~/.config/nvim nvim-config/
          cp -r ~/.local/share/nvim/lazy nvim-config/plugins
          tar czf nvim-config.tar.gz nvim-config

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "v1.0.${{ github.run_number }}"
          release_name: "Neovim Config Release v1.0.${{ github.run_number }}"
          draft: false
          prerelease: false

      - name: Upload snapshot to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: "./lazy-lock.json"
          asset_name: "lazy-lock.json"
          asset_content_type: "application/json"

      - name: Upload plugins to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: "./plugins.tar.gz"
          asset_name: "plugins.tar.gz"
          asset_content_type: "application/gzip"

      - name: Upload full configuration to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: "./nvim-config.tar.gz"
          asset_name: "nvim-config.tar.gz"
          asset_content_type: "application/gzip"

